on:
  push:
    branches:
      - main

name: "Shellcheck"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
        env:
          SHELLCHECK_OPTS: -e SC2086
# Shellcheck options SC2086 - Double quote to prevent globbing and word splitting. 
# https://www.shellcheck.net/wiki/SC2086
